### ISSUE TITLE
Please remove any unnecessary state variables that are not being utilized, as well as some functions. You can refer to the screenshots.

### ISSUE THREAD

**Issue by smegcoffee** [smegcoffee/request_form#56]
![image](https://github.com/user-attachments/assets/9fee4219-d704-49b9-bf09-a200e47cd4f5)
![image](https://github.com/user-attachments/assets/9e4f9e94-261d-419d-89c3-1406043d6aae)
![image](https://github.com/user-attachments/assets/f4454811-6c91-4b4e-bc5e-6122e93a9d60)
![image](https://github.com/user-attachments/assets/474e1342-32c7-4eb4-8cb7-d8e1ff6dbca0)

**Comment by noreenswan10** [comment]
There are some unused state variables but their setVariable was being used in a function. But not being used inside the XML.
Example:
![image](https://github.com/user-attachments/assets/504cf020-f1b9-4168-b3d6-5652930bb781)
I did not delete that line since the set has been used inside a function and maybe it will be used in the future? The (e.g. initialNotedBy and initialApprovedBy)??
Vice versa, example:
![image](https://github.com/user-attachments/assets/213aa3a1-3c27-4ff0-8665-7021d756a419)
It was used inside the XML but did not have a function, is there still a chance to use these in the future? If not, let me know to delete these unnecessaries.
P.S. Both situations are useless but needed confirmation about its importance to avoid destruction of the system.

**Comment by smegcoffee** [comment]
We will review that one, but all the major tasks have already been addressed. Great work!
